### ISSUE TITLE
if 'not-exist.com' then None

### ISSUE THREAD

**Issue by Sam1808** [kyan001/ping3#1]
Good day!
Your wrote ">>> ping('not-exist.com')  # If timed out (no reply), returns None"
But I think, that it`s right only for IP addresses. 
If we use 'not-exist domain name', then
>>> ping('not-exist.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python36-32\lib\site-packages\ping3.py", line 121, in ping
    send_one_ping(my_socket, dest_addr, my_ID)
  File "C:\Python\Python36-32\lib\site-packages\ping3.py", line 86, in send_one_ping
    dest_addr = socket.gethostbyname(dest_addr)
socket.gaierror: [Errno 11001] getaddrinfo failed

Thank you!

**Comment by kyan001** [comment]
Hi @Sam1808,

Thanks for pointing out this problem.

The reason of such a exception is "not-exist.com" does not has a DNS record. If a domain name has a DNS record (pointing to an IP address), but that IP address does not responding to ping, then this command should work (returns None). So it's not because you put a domain name (instead of an IP address) as the argument, it's because I use a bad example domain name. Sorry about this.

I will change it from "not-exist.com" (no DNS record) to "notexist.com" (has a DNS record), maybe this website has a response to ping command, but at least it has a DNS record to avoid that exception.

and yes, any IP address does not have a server behind should work too.

Thanks again for your feedback.
