### ISSUE TITLE
多进程ping不同ip结果不准确，不通的ip都能通？

### ISSUE THREAD

**Issue by liaozhizhong16** [kyan001/ping3#20]
import multiprocessing as mp
    pool=mp.Pool()
    result=pool.map(verbose_ping,(arg,arg2))
    print(result)

**Comment by kyan001** [comment]
Hi @liaozhizhong16 ,

Sorry for the waitings.
I did not reproduce this problem on both Win10 and WSL. But I guess there are something I can do.
This problem may caused by the identical IDs given by threading.currentThread.ident. On some OS, the thread id has the same last N digits -- such as 31222 and 41222 -- instead of same first N digits. In this case, the ICMP_ID will has the same number, which will cause ping cannot distinguish incoming packets.

The solution here is to alter the way of ICMP_ID generating. I use checksum(thread_id) to get new icmp id. In addition, for who use python >= 3.8, ping is using `threading.get_native_id()` to get thread_id. This should give the real thread id to icmp_id. 

All the updates should be available in version >= 2.4.6, but Pypi is now under maintainance. I will try to upload the new version ASAP. Hope this should solve the problem.

If it happens again, some logs with debug mode enabled would be great help. (`ping3.DEBUG =True`).

**Comment by kyan001** [comment]
Please let me know if this problem still exist.
