### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Tes3awy** [kyan001/ping3#37]
Hello @kyan001 ,

I would like to take the opportunity to thank you so much for this package as it saved the day many times.

Hope you are doing well. I was wondering why does the `ping3.ping("example.com")` returns delay in seconds instead of returning a boolean value? 

I think it would make sense if the IP address I am pinging is reachable it returns `True`, otherwise it returns `False`. So that when I use it to check the reachability of some hosts in my LAN, I would write something like:

```python
import ping3

ip = "192.168.1.1"
if ping3.ping(ip):
    print(f"{ip} is reachable")
else:
   print(f"{ip} is unreachable")
```

I know that values other than 0 are evaluated to `True` in `if statements` and a value like `0.215697261510079666` is `True`. But I think it's more of a Pythonic way.

Thank you for your consideration.

**Comment by kyan001** [comment]
Hi @Tes3awy, sorry for the late response.

`ping3.ping()` returns delay instead of a boolean value, is based on the following reasons:
1. Delay provides more information than boolean value. Delay shows not only yes/no, but also "how yes it is".
2. `ping()` returns delay is convertional.
3. Delay is also recommanded to be "Truth Value Testing" through a if statement in python. [Here is the offical guide](https://docs.python.org/3/library/stdtypes.html?highlight=int#truth-value-testing). By default, an object is considered true unless its class defines either a `__bool__()` method that returns False or a `__len__()` method that returns zero. That's the offical way to use numbers with if.

The code you provided is pretty Pythonic and also not too Pythonic. That's a good piece of code, you can use it in your codes without any hesitation.
