### ISSUE TITLE
End hop on errors.TimeToLiveExpired

### ISSUE THREAD

**Issue by tieugene** [kyan001/ping3#48]
Is it possible to get finishing hop IP on ttl expired?
And time.
This will help to simulate "traceroute" behaviour.

**Comment by kyan001** [comment]
Hi @tieugene ,

Currently you can only get the last hop IP when ttl expired from the console DEBUG mode outputs.

I was thinking about to add the IP header and the ICMP header into the ttl expired exception. But by doing this, only IP address is passed, the delay will not included since the sent time is not mentioned in the ttl expired message. What you can do is to log the start time and the end time before/after ping() was called, and calculate the time difference as the delay. The traceroute feature sounds like an application of ping to me, so I don't want to do the full implement of it in ping3.

The headers info in exception will break the interface of ping3, so it might comes with v4.0.0.

Thanks for your suggestion.

**Comment by tieugene** [comment]
> Currently you can only get the last hop IP when ttl expired from the console DEBUG mode outputs.
I think "and time" is too much, IP is enough.
I tried to simulate traceroute intercepting errors.TimeToLiveExpired, but cannot find how to get intermediate hop IP.
The only information that I need - ping has reached some hope in route (without time is enough).

**Comment by kyan001** [comment]
OK, let me work on that. I'll let you know when it comes out.

**Comment by kyan001** [comment]
@tieugene Hi,

Now the ping3 is updated to 4.0.0. Please update and try.

You can get the end hop IP address by the following code:
```py
try:
     ping3.ping("example.com", ttl=1)
except ping3.errors.TimeToLiveExpired as err:
    print(err.ip_header["src_addr"])
```
