### ISSUE TITLE
ping never ends while pc is hibernated

### ISSUE THREAD

**Issue by ikino** [kyan001/ping3#56]
If I ping something with timeout 3s, hibernate PC and then wake up next day, ping is never end. Linux.

**Comment by kyan001** [comment]
Hi @ikino ,

I tested on Win11, the ping can still return when I hibernate my PC.

If you can run the same code with `ping3.DEBUG = True` and send me the outputs, that would be a great help to address the problem. For now, I guess this is something about `select` function implementation in Linux, and I can't do nothing about it.

If you run into this problem again, you can press `Ctrl + C` to force stop the program, and rerun the code after it as a workaround. Because it's not an usual case, I just leave it and wait for your debug outputs. So if this is pretty important to you, leave me a message and let's do some more research about it.

Thanks for your feedback!
