### ISSUE TITLE
Inconsistency between ping and verbose_ping: count parmameter and return value

### ISSUE THREAD

**Issue by kmille** [kyan001/ping3#66]
Hey,

there are some things I don't understand:
- why does `verbose_ping` has a parmeter `count`, but `ping` doesn't?
- why does `ping` return a value (seconds or an error), `verbose_ping` returns nothing (even if the comment says: `Returns:  formatted ping results printed.`)?

Can you fix this and make it a bit more consistent?

**Comment by kyan001** [comment]
Hi @kmille

`verbose_ping()` is an alternative to the shell `ping` command. It sends multiple ping messages sequentially. The `count` parameter specifies how many ping messages `verbose_ping()` sends. In contrast, the `ping()` function only sends one ping message per call, so it does not require a `count` parameter, as the count is always 1.

The function `ping()` is designed to be used by other functions within a program, and it returns a value which can be further used for processing. In contrast, `verbose_ping()` is intended to be used directly in the terminal interactively, and instead of returning the result, it prints the result to the standard output. This allows the user to view the ping result without having to explicitly process the return value.

Feel free to ask me if you have any further questions.

Kyan
